name: honegumi_rag_assistant
channels:
  - defaults
  - conda-forge
  - pytorch
  # - fastai
dependencies:
  - python>=3.11
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  - click
  - ipython
  # VISUALIZATION
  - matplotlib
  - ipympl  # interactive matplotlib plots
  - seaborn
  # - altair
  # - yellowbrick
  # ML, STATS & DEEP LEARNING
  # - statsmodels
  # - scikit-learn
  # - sktime
  # - tslearn
  # - xgboost
  # - catboost
  # - lightgbm
  # - pytorch
  # - fastai  # activate fastai channel above!
  # - tensorflow
  # - keras
  # - spacy
  # OTHER TOOLS
  # - optuna
  # - dask
  # - snakeviz
  - pip:
     - -e .  # install git checkout of honegumi_rag_assistant in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib
     - openai==2.3.0
     - langchain_openai==0.3.35
     - honegumi==0.4.3
     - langchain==0.3.27
     - langchain_community==0.3.31
     - langgraph==0.6.10
     - faiss-cpu==1.12.0

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
